[build]
builder = "nixpacks"

[deploy]
startCommand = "bin/rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"
