input:
  text_field:
    base: "form-field__input shadow-sm block w-full sm:text-sm rounded-md"
    clean: "form-field__input focus:ring-gray-500 focus:border-gray-500 border-gray-300"
    error: "form-field__input focus:ring-red-500 focus:border-red-500 border-red-300"
  text_area:
    base: "form-field__input shadow-sm block w-full sm:text-sm border rounded-md"
    clean: "form-field__input focus:ring-gray-500 focus:border-gray-500 border-gray-300"
    error: "form-field__input focus:ring-red-500 focus:border-red-500 border-red-300"
  text_field_leading:
    base: "form-field__input block w-full pl-7 sm:text-sm rounded-md"
    clean: "form-field__input focus:ring-gray-500 focus:border-gray-500 border-gray-300"
    error: "form-field__input focus:ring-red-500 focus:border-red-500 border-red-300"
